version: '3'
services:
    web:
        build: .
        restart: always
        ports:
            - "5000:5000"
        env_file:
            - web-variables.env
        volumes:
            - ./website/data:/app/website/data
    broker:
        image: eclipse-mosquitto:1.6
        ports: 
            - "1883:1883"
        volumes:
            - ./mqtt_config:/mosquitto/config:ro
        restart: always
