version: '3'
services:
    web:
        build: .
        restart: always
        ports:
            - "5000:5000"
        env_file:
            - web-variables.env
        volumes:
            - ./website/data:/app/website/data
